ARG JDK_VERSION=11
FROM openjdk:${JDK_VERSION}-jdk-slim
ARG JAR=/build/libs/app.jar
ARG EXPOSE=8080
ENV EXPOSE=${EXPOSE}
ENV DATABASE_URL=$DATABASE_URL
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV DATABASE_USER=$DATABASE_USER

EXPOSE ${EXPOSE}

COPY ${JAR} app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]