spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/otp-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog.xml